### ISSUE TITLE
Regional setting

### ISSUE THREAD

**Issue by olivercortinas** [Giorgi/Math-Expression-Evaluator#5]
Hi, i have an issue with the regional setting of 2 pc running the same code, the issue is that one of them has configured regional setting as spanish with decimal sign as "." and the other is english with decimal sign as ",". If we use a decimal value on the format "1.002", for example, on the formula the spanish evaluate the formula ok and the english not. There is no way to set culture info to avoid this problem?
Otherwise we have to replace string before evaluate.

**Comment by Giorgi** [comment]
You can pass CultureInfo which specified the settings you have. See this example: [CultureInfo test](https://github.com/Giorgi/Math-Expression-Evaluator/blob/a6b6f1d9fddb64ea9b7c338350f69aabd2d221fb/SimpleExpressionEvaluator.Tests/ExpressionEvaluatorTests.cs#L165)
